import 'package:flutter/material.dart';
import 'package:weather_app/domains/weather_model/weather_data_model.dart';

class ModelWeatherDayWidget extends StatelessWidget {
  final Autogenerated weather;
  final int index;

  const ModelWeatherDayWidget(
      {Key? key, required this.weather, required this.index})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        children: [
          Text(
            weather.list![index].dtTxt.toString().split(' ')[0],
            style: TextStyle(color: Colors.white),
          ),
          Image.network(
              'http://openweathermap.org/img/wn/${weather.list![index].weather![0].icon}.png'),
          Text('${weather.list![index].main?.temp}',style: TextStyle(color: Colors.white),)
        ],
      ),
    );
  }
}
