import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:weather_app/pages/main_page/widgets/days_weather_widget.dart';
import 'package:weather_app/pages/main_page/widgets/hours_weather_widget.dart';
import 'package:weather_app/pages/main_page/widgets/model_hour_weather_widget.dart';
import 'package:weather_app/util/images/images_data.dart';

import '../../domains/api_clients/api_client.dart';
import '../../domains/weather_model/weather_data_model.dart';
import '../../util/text_styles/text_styles.dart';

Autogenerated? _weather;
bool getWeather = false;

class MainPage extends StatefulWidget {
  const MainPage({Key? key}) : super(key: key);

  @override
  State<MainPage> createState() => _MainPageState();
}

class _MainPageState extends State<MainPage> {

  List<String> items = ['Days', 'By the hour'];
  String? selectedItem;
  double bottomTableSize=440;
  bool nightTheme = true;
  String city="Kropyvnytskyi";
  @override
  Widget build(BuildContext context) {
    ApiClient apiClient = ApiClient(city);
    void reloadPost() async {
      var weather = await apiClient.getWeather();
      if(weather.message != null && weather.message == "city not found")
        {
          apiClient = ApiClient(city="London");
          print('+');
          weather = await apiClient.getWeather();
        }
      setState(() => _weather = weather);
    }

    if (!getWeather) {
      reloadPost();
      getWeather = true;
    }

    if (_weather != null) {
      return Scaffold(
        body: DecoratedBox(
          decoration:  BoxDecoration(
            image: DecorationImage(
                image: setBackground(),
                fit: BoxFit.cover),
          ),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
               Padding(
                padding: const EdgeInsets.all(16.0),
                child: TextField(
                    onSubmitted: (text) {
                      apiClient=ApiClient(text);
                      city=text;
                      reloadPost();
                      print("+");
                    },
                    style: TextStyles.cityFindTextStyle,
                    decoration: InputDecoration(
                        hintStyle: TextStyle(color:  nightTheme ? Colors.white70: Colors.black87),
                        hintText: 'city',
                        enabledBorder: UnderlineInputBorder(
                            borderSide:
                            BorderSide(width: 2.0, color: nightTheme ? Colors.white : Colors.black87)),
                        focusedBorder: UnderlineInputBorder(
                            borderSide:
                            BorderSide(width: 1.0, color:  nightTheme ? Colors.white60: Colors.black87)),
                        isCollapsed: true,
                        contentPadding: const EdgeInsets.only(top: 16.0),
                        prefixIcon: Icon(
                          Icons.location_city,
                          color:  nightTheme ? Colors.white70: Colors.black87,
                        ))),
              ),
              Text(city,
                  style: TextStyle(
                      color: nightTheme ? Colors.white70: Colors.black87,
                      fontSize: 35,
                      fontWeight: FontWeight.w300)),
              Text(' ${(_weather?.list![0].main?.temp?.toInt()).toString()}°',
                  style: TextStyle(
                      color: nightTheme ? Colors.white70: Colors.black87,
                      fontSize: 70,
                      fontWeight: FontWeight.w300)),
              Text((_weather?.list![0].weather![0].description).toString(),
                  style: TextStyle(
                      color: nightTheme ? Colors.white70: Colors.black87,
                      fontSize: 20,
                      fontWeight: FontWeight.w300)),
              Spacer(),
              Spacer(),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 8.0),
                child: Container(
                  child: Align(
                    alignment: Alignment.centerRight,
                    child: DropdownButtonFormField<String>(
                        dropdownColor: Colors.black54,
                        iconEnabledColor: Colors.white,
                        iconDisabledColor: Colors.white,
                        value: selectedItem,
                        hint: const Text("Days / by the hour",
                            style:
                            TextStyle(fontSize: 17, color: Colors.white)),
                        items: items
                            .map((item) =>
                            DropdownMenuItem<String>(
                              value: item,
                              child: Text(item,
                                  style: const TextStyle(
                                      fontSize: 17, color: Colors.white)),
                            ))
                            .toList(),
                        onChanged: (item) =>
                            setState(() => selectedItem = item)),
                  ),
                ),
              ),
              Expanded(
                child: Container(
                  decoration: const BoxDecoration(
                    border: Border(
                      top: BorderSide(width: 2.5, color: Colors.white),
                    ),
                    color: Colors.black54,
                  ),
                  child: Center(
                    child: selectedItem == "By the hour"
                        ? HoursWeatherWidget(weather: _weather!)
                        : DaysWeatherWidget(weather: _weather!),
                  ),
                ),
              ),
            ],
          ),
        ),
      );
    } else {
      return const Scaffold(body: Center(child: Text('Wait weather data')));
    }
  }

  setTemperatureFromFahrenheitToCelsius(double? temp) {
    double celsius = temp!;
    return (celsius - 32) * 5 ~/ 9;
  }

  setBackground() {
    if (ModelWeatherHourWidget.getOnlyHour(
        _weather!.list![0].dtTxt.toString()) == "00:00:00" ||
        ModelWeatherHourWidget.getOnlyHour(
            _weather!.list![0].dtTxt.toString()) == "03:00:00") {
      return BackgroundImage.backgroundNightImage;
    }
    if (ModelWeatherHourWidget.getOnlyHour(
        _weather!.list![0].dtTxt.toString()) == "06:00:00" ||
        ModelWeatherHourWidget.getOnlyHour(
            _weather!.list![0].dtTxt.toString()) == "09:00:00") {
      return BackgroundImage.backgroundMorningImage;
    }
    if (ModelWeatherHourWidget.getOnlyHour(
        _weather!.list![0].dtTxt.toString()) == "18:00:00" ||
        ModelWeatherHourWidget.getOnlyHour(_weather!.list![0].dtTxt.toString())=="21:00:00")
    {
      return BackgroundImage.backgroundEveningImage;
    }
    nightTheme=false;
    return BackgroundImage.backgroundDayImage;
  }

}

